 SELECT test_plantdb_vegetationview.row_number,
    test_plantdb_vegetationview.picturelist,
    test_plantdb_vegetationview.vegetationid,
    test_plantdb_vegetationview.plantid,
    test_plantdb_vegetationview.rootstockid,
    test_plantdb_vegetationview.cultivarid,
    test_plantdb_vegetationview.legacy_pfaf_latin_name,
    test_plantdb_vegetationview.family,
    test_plantdb_vegetationview.genus,
    test_plantdb_vegetationview.species,
    test_plantdb_vegetationview.ssp,
    test_plantdb_vegetationview.common_name,
    test_plantdb_vegetationview.plant_function,
    test_plantdb_vegetationview.border_colour,
    test_plantdb_vegetationview.fill_colour,
    test_plantdb_vegetationview.symbol,
    test_plantdb_vegetationview.form,
    test_plantdb_vegetationview.locations,
    test_plantdb_vegetationview.width,
    test_plantdb_vegetationview.height,
    test_plantdb_vegetationview.grafted,
    test_plantdb_vegetationview.comment,
    test_plantdb_vegetationview.germination_date,
    test_plantdb_vegetationview.habitat,
    test_plantdb_vegetationview.wind_lower_limit,
    test_plantdb_vegetationview.wind_upper_limit,
    test_plantdb_vegetationview.light_lower_limit,
    test_plantdb_vegetationview.light_upper_limit,
    test_plantdb_vegetationview.nitrogen_fixer,
    test_plantdb_vegetationview.supports_wildlife,
    test_plantdb_vegetationview.flower_type,
    test_plantdb_vegetationview.pollinators,
    test_plantdb_vegetationview.self_fertile,
    test_plantdb_vegetationview.pollution,
    test_plantdb_vegetationview.cultivation_details,
    test_plantdb_vegetationview.known_hazards,
    test_plantdb_vegetationview.cultivarname,
    test_plantdb_vegetationview.notes_on_cultivar,
    test_plantdb_vegetationview.synonyms,
    test_plantdb_vegetationview.scented,
    test_plantdb_vegetationview.wind_tolerance,
    test_plantdb_vegetationview.hardiness,
    test_plantdb_vegetationview.range,
    test_plantdb_vegetationview.frost_tender,
    test_plantdb_vegetationview.production_startmonth,
    test_plantdb_vegetationview.production_endmonth,
    test_plantdb_vegetationview.leaf_startmonth,
    test_plantdb_vegetationview.leaf_endmonth,
    test_plantdb_vegetationview.flower_startmonth,
    test_plantdb_vegetationview.flower_endmonth,
    test_plantdb_vegetationview.seed_start_month,
    test_plantdb_vegetationview.seed_endmonth,
    test_plantdb_vegetationview.rootstockname,
    test_plantdb_vegetationview.notes_on_rootstock,
    test_plantdb_vegetationview.vigour,
    test_plantdb_vegetationview."pH_lower_limit",
    test_plantdb_vegetationview."pH_upper_limit",
    test_plantdb_vegetationview.salinity_lower_limit,
    test_plantdb_vegetationview.salinity_upper_limit,
    test_plantdb_vegetationview.moisture_lower_limit,
    test_plantdb_vegetationview.moisture_upper_limit,
    test_plantdb_vegetationview.soiltexture_lower_limit,
    test_plantdb_vegetationview.soiltexture_upper_limit
   FROM ( SELECT row_number() OVER (ORDER BY plantdb_vegetation.id) AS row_number,
            plantdb_vegetation.id AS vegetationid,
            plantdb_plant.id AS plantid,
            plantdb_plant.legacy_pfaf_latin_name,
            plantdb_plant.family,
            plantdb_plant.genus,
            plantdb_plant.species,
            plantdb_plant.ssp,
            plantdb_plant.common_name,
            plantdb_plant.plant_function,
            plantdb_plant.border_colour,
            plantdb_plant.fill_colour,
            plantdb_plant.symbol,
            plantdb_plant.form,
            plantdb_vegetation.locations,
            plantdb_rootstock.id AS rootstockid,
            plantdb_rootstock.height,
            plantdb_rootstock.width,
            plantdb_cultivar.id AS cultivarid,
            plantdb_cultivar.production_startmonth,
            plantdb_cultivar.production_endmonth,
            plantdb_vegetation.grafted,
            plantdb_vegetation.comment,
            plantdb_vegetation.germination_date,
            plantdb_plant.habitat,
            plantdb_plant.wind_lower_limit,
            plantdb_plant.wind_upper_limit,
            plantdb_plant.light_lower_limit,
            plantdb_plant.light_upper_limit,
            plantdb_plant.nitrogen_fixer,
            plantdb_plant.supports_wildlife,
            plantdb_plant.flower_type,
            plantdb_plant.pollinators,
            plantdb_plant.self_fertile,
            plantdb_plant.pollution,
            plantdb_plant.cultivation_details,
            plantdb_plant.known_hazards,
            plantdb_cultivar.name AS cultivarname,
            plantdb_cultivar.notes_on_cultivar,
            plantdb_cultivar.synonyms,
            plantdb_cultivar.scented,
            plantdb_cultivar.wind_tolerance,
            plantdb_cultivar.hardiness,
            plantdb_cultivar.range,
            plantdb_cultivar.frost_tender,
            plantdb_cultivar.leaf_startmonth,
            plantdb_cultivar.leaf_endmonth,
            plantdb_cultivar.flower_startmonth,
            plantdb_cultivar.flower_endmonth,
            plantdb_cultivar.seed_start_month,
            plantdb_cultivar.seed_endmonth,
            plantdb_rootstock.rootstockname,
            plantdb_rootstock.notes_on_rootstock,
            plantdb_rootstock.vigour,
            plantdb_rootstock."pH_lower_limit",
            plantdb_rootstock."pH_upper_limit",
            plantdb_rootstock.salinity_lower_limit,
            plantdb_rootstock.salinity_upper_limit,
            plantdb_rootstock.moisture_lower_limit,
            plantdb_rootstock.moisture_upper_limit,
            plantdb_rootstock.soiltexture_lower_limit,
            plantdb_rootstock.soiltexture_upper_limit,
            string_agg(plantdb_cultivarimage.picture, ',') AS picturelist
           FROM plantdb_vegetation
             LEFT JOIN plantdb_plant ON plantdb_vegetation.plant_id = plantdb_plant.id
             LEFT JOIN plantdb_cultivar ON plantdb_vegetation.cultivar_id = plantdb_cultivar.id
             LEFT JOIN plantdb_rootstock ON plantdb_vegetation.rootstock_id = plantdb_rootstock.id
             LEFT JOIN plantdb_cultivarimage ON plantdb_vegetation.cultivar_id = plantdb_cultivarimage.cultivar_id
            GROUP BY plantdb_vegetation.id,plantdb_plant.id,plantdb_rootstock.id,plantdb_cultivar.id) test_plantdb_vegetationview;


